apiVersion: v1
kind: Namespace
metadata:
  name: expiration-watcher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expiration-watcher-svc-account
  namespace: expiration-watcher
  labels:
    app: expiration-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expiration-watcher-cluster-role
  labels:
    app: expiration-watcher
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expiration-watcher-binding
  labels:
    app: expiration-watcher
subjects:
- kind: ServiceAccount
  name: expiration-watcher-svc-account
  namespace: expiration-watcher
roleRef:
  kind: ClusterRole
  name: expiration-watcher-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expiration-watcher
  name: expiration-watcher
  namespace: expiration-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: expiration-watcher
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: expiration-watcher-svc-account
      containers:
      - image: expiration-watcher/expiration-watcher:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            protocol: TCP
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 5
        name: expiration-watcher
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      terminationGracePeriodSeconds: 5